# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python
name: Build
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarcloud:
    name: SonarCloud
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 80
      - name: Installation Python 3.8.10
        uses: actions/setup-python@v2
        with:
          python-version: 3.8.10
      - name: Installation dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
          pip install pylint pytest pytest-cov selenium playwright
      - uses: actions/upload-artifact@v2
        with:
          name: code-coverage
          path: htmlcov
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        with:
          targetBranch: master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}